from datetime import date, timedelta
from app.core.database import Base, engine, SessionLocal
from app.models.models import *
from app.services.risk_scoring import calculate_event_score
TAXA=[("Lanthanotus borneensis","Borneo earless monitor","lizard","II","B",["Indonesia","Malaysia"],"Distinctive limbless-looking monitor; verify permits and declared source."),("Naultinus spp.","New Zealand green geckos","gecko","II","B",["New Zealand"],"Bright green arboreal geckos; verify lawful origin documentation."),("Cuora trifasciata","Golden coin turtle","turtle","II","B",["China","Vietnam","Laos"],"Box turtle with yellow striping; check source claims carefully."),("Uroplatus spp.","Leaf-tailed geckos","gecko","II","B",["Madagascar"],"Cryptic leaf-tailed geckos; verify export/import documentation."),("Varanus prasinus complex","Green tree monitor complex","lizard","II","B",["Indonesia","Papua New Guinea"],"Arboreal green monitors; verify species ID and origin."),("Lygodactylus williamsi","Electric blue day gecko","gecko","I","A",["Tanzania"],"Small bright blue gecko; high conservation concern."),("Brachylophus spp.","Fiji iguanas","lizard","I","A",["Fiji"],"Green iguanas with banding; verify legal status and origin."),("Cyclura spp.","Rock iguanas","lizard","I/II","A/B",["Caribbean"],"Large island iguanas; verify species and paperwork."),("Smaug spp.","Giant girdled lizards","lizard","II","B",["South Africa"],"Spiny cordylids; verify origin and permits."),("Cuora pani","Pan's box turtle","turtle","II","B",["China"],"Rare box turtle; recommended expert ID verification.")]
EVENTS=[("Terraristika Hamm","terraristika-hamm","Hamm","Germany",51.681,-7.816,"Zentralhallen Hamm","high"),("Terraria Houten","terraria-houten","Houten","Netherlands",52.034,5.168,"Expo Houten","medium"),("Prague reptile/exotics fair","prague-reptile-exotics-fair","Prague","Czech Republic",50.075,14.438,"PVA Expo Praha","medium"),("Verona Reptiles","verona-reptiles","Verona","Italy",45.438,10.991,"Veronafiere","medium"),("NARBC Tinley Park","narbc-tinley-park","Tinley Park","USA",41.573,-87.784,"Tinley Park Convention Center","medium"),("Japan Reptiles Show","japan-reptiles-show","Shizuoka","Japan",34.975,138.383,"Twin Messe Shizuoka","medium"),("Canadian Reptile Breeders Expo","canadian-reptile-breeders-expo","Toronto","Canada",43.653,-79.383,"International Centre placeholder","weak"),("Repticon Orlando","repticon-orlando","Orlando","USA",28.538,-81.379,"Central Florida Fairgrounds","weak"),("Expo Terraristika Latin America placeholder","expo-terraristika-latin-america","São Paulo","Brazil",-23.55,-46.633,"São Paulo expo placeholder","unknown"),("Bangkok exotic pet market placeholder","bangkok-exotics-placeholder","Bangkok","Thailand",13.756,100.501,"Bangkok market area placeholder","unknown")]
AIRPORTS={"Germany":[("DUS","Düsseldorf","Germany"),("FRA","Frankfurt","Germany")],"Netherlands":[("AMS","Amsterdam","Netherlands"),("EIN","Eindhoven","Netherlands")],"Czech Republic":[("PRG","Prague","Czech Republic"),("VIE","Vienna","Austria")],"Italy":[("VRN","Verona","Italy"),("MXP","Milan","Italy")],"USA":[("ORD","Chicago","USA"),("MCO","Orlando","USA")],"Japan":[("NRT","Tokyo Narita","Japan"),("HND","Tokyo Haneda","Japan")],"Canada":[("YYZ","Toronto","Canada"),("YUL","Montreal","Canada")],"Brazil":[("GRU","São Paulo","Brazil"),("GIG","Rio de Janeiro","Brazil")],"Thailand":[("BKK","Bangkok Suvarnabhumi","Thailand"),("DMK","Bangkok Don Mueang","Thailand")]}
def seed():
    Base.metadata.create_all(engine); db=SessionLocal()
    if db.query(Event).count(): return
    db.add(Organization(name="ExpoWatch MVP Partner Network"));
    taxa=[]
    for t in TAXA:
        taxa.append(Taxon(scientific_name=t[0],common_name=t[1],taxon_group=t[2],cites_appendix=t[3],eu_annex=t[4],native_range_countries=t[5],origin_countries=t[5],transit_countries=["Singapore","Netherlands","United Arab Emirates"],id_notes=t[6])); db.add(taxa[-1])
    for name,slug,city,country,lat,lon,venue,conf in EVENTS:
        v=Venue(name=venue,city=city,country=country,latitude=lat,longitude=lon,geom_wkt=f"POINT({lon} {lat})"); db.add(v); db.flush()
        e=Event(name=name,slug=slug,venue_id=v.id,description="Internal monitoring-priority profile using cautious OSINT language; route-risk intersections require partner verification.",confidence=conf); db.add(e); db.flush()
        start=date(2026,8,15)+timedelta(days=len(slug)%90); db.add(EventDate(event_id=e.id,start_date=start,end_date=start+timedelta(days=1)))
        for i,(iata,ac,acountry) in enumerate(AIRPORTS.get(country,AIRPORTS["USA"])):
            if not db.query(Airport).filter_by(iata=iata).first():
                db.add(Airport(iata=iata,name=f"{ac} Airport",city=ac,country=acountry,latitude=lat+i,longitude=lon+i,geom_wkt=f"POINT({lon+i} {lat+i})"))
        selected=taxa[:5] if conf in ["high","medium"] else taxa[3:8]
        for tx in selected: db.add(EventTaxon(event_id=e.id,taxon_id=tx.id,reason_for_inclusion="Proxy taxon included as a monitoring priority indicator; presence is not proof of criminality.",evidence_basis="historical trade concern",confidence="medium" if conf!="unknown" else "low"))
        site_types=["official event site","seller forum","classifieds","courier/import-export service","journalist report"]
        for st in site_types[:4]:
            w=Website(name=f"{name} {st}",url=f"https://example.org/{slug}/{st.replace('/','-')}",type=st,notes="Seeded public/open-source reference placeholder for analyst review.",confidence="weak" if conf=="unknown" else "likely",last_checked_date=date(2026,6,1)); db.add(w); db.flush(); db.add(EventWebsite(event_id=e.id,website_id=w.id))
        origins=["Indonesia","Madagascar","Vietnam"]; consumers=["United States","Germany","Japan"]
        for o in origins: db.add(RouteRisk(event_id=e.id,direction="inbound",origin=o,destination=country,transit_hubs=["Singapore","Doha"],window_start=start-timedelta(days=14),window_end=start,rationale="Mock route-risk intersection between possible origin country and expo country; recommended verification point only.",confidence="low" if conf=="unknown" else "medium"))
        for c in consumers: db.add(RouteRisk(event_id=e.id,direction="outbound",origin=country,destination=c,transit_hubs=["Amsterdam","Dubai"],window_start=start,window_end=start+timedelta(days=7),rationale="Mock outbound consumer-region feasibility indicator; not proof of criminality.",confidence="low" if conf=="unknown" else "medium"))
        for n in range(3): db.add(EvidenceItem(title=f"{name} evidence placeholder {n+1}",evidence_type=["official event page","journalist report","attendee report"][n],url=f"https://example.org/evidence/{slug}/{n}",date_observed=date(2026,6,1),event_id=e.id,related_taxa=[selected[n].scientific_name],summary="Manual evidence placeholder for lawful OSINT tracking and verification.",extracted_red_flags=["source claim requires verification","proxy taxon mention"],analyst_notes="Seed record; preserve URL/date if replaced with real evidence.",confidence="weak" if conf=="unknown" else "medium"))
        db.flush(); score=calculate_event_score(e); db.add(RiskScore(event_id=e.id,**score)); db.add(LeadPackage(event_id=e.id,title=f"{name} lead package preview",html="<p>MVP saved preview. Generate current preview from event detail.</p>",caveat="This is an intelligence lead package, not proof of criminality."))
    db.add(User(email="analyst@example.org",role="analyst")); db.commit(); db.close()
if __name__=="__main__": seed()
